dist: trusty
sudo: false
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
if: tag IS blank


jobs:
  include:
    - stage: build and publish
      language: java
      jdk: openjdk11
      install: skip
      script: ./gradlew clean build
      before_deploy:
        - git config --local user.name "jeyakumard-coder"
        - git config --local user.email "mailjeyk@gmail.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: 165f6b0c36c769397314aecd1cd0da21e89ca98f
        file: "build/libs/pal-tracker.jar"
        skip_cleanup: true
    - stage: deploy to cf
      language: bash
      script:
        - echo "Downloading $RELEASE_TAG"
        - wget -P build/libs https://github.com/$GITHUB_USERNAME/pal-tracker/releases/download/$RELEASE_TAG/pal-tracker.jar
      before_deploy:
        - echo "Deploying $RELEASE_TAG to Cloud Foundry"
      deploy:
        provider: cloudfoundry
        api: https://api.sys.evans.pal.pivotal.io
        username: jeyakumar.datchinamoorthi@voya.com
        password: x2vgjvxk
        organization: jeyakumar.datchinamoorthi.voya.com
        space: sandbox
